### ISSUE TITLE
Requires manually downgrading to pg@6.4.1

### ISSUE THREAD

**Issue by alexcberk** [nsatter/sequelize-templates#1]
Throws `TypeError: connection.query(...).on is not a function` if you have pg@7.0+ installed. Had to run `npm i -g pg@6.4.1` to run. 

Updating the sequelize dependency may solve this.
https://github.com/sequelize/sequelize/issues/7977

**Comment by nsatter** [comment]
I needed to update the dependencies to add support for pg 7.

This is fixed in release v0.2
